# Generated by Django 2.2 on 2022-01-21 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('description', models.TextField(verbose_name='question description')),
                ('file', models.FileField(max_length=200, upload_to='quiz/resources/%Y/%m', verbose_name='question file')),
                ('question_type', models.CharField(choices=[('mcq', 'multiple choice question'), ('mcsq', 'multiple choices question'), ('tfq', 'true/false question')], max_length=4, verbose_name='question type')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'question',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('name', models.CharField(max_length=150, verbose_name='quiz name')),
                ('quiz_type', models.CharField(choices=[('pre-test', 'preview test'), ('post-test', 'post test'), ('review-test', 'review test')], max_length=10, verbose_name='quiz type')),
                ('questions', models.ManyToManyField(to='quizzes.Question')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('answer', models.TextField(verbose_name='question answer')),
                ('answer_type', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=4, verbose_name='answer type')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'question answer',
                'verbose_name_plural': 'question answer',
            },
        ),
    ]
