# Generated by Django 2.2 on 2022-03-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
