# Generated by Django 2.2 on 2022-03-24 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('course_id', models.CharField(max_length=10, unique=True, verbose_name='course id number')),
            ],
            options={
                'verbose_name': 'course information',
                'verbose_name_plural': 'course information',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('name', models.CharField(max_length=20, verbose_name='lecturer name')),
                ('teacher_id', models.CharField(max_length=10, unique=True, verbose_name='teacher id number')),
                ('website', models.URLField(verbose_name='lecturer link')),
            ],
            options={
                'verbose_name': 'course lecturer',
                'verbose_name_plural': 'course lecturer',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('name', models.CharField(max_length=50, verbose_name='lesson name')),
                ('lesson_id', models.CharField(max_length=10, verbose_name='chapter number')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course lesson',
                'verbose_name_plural': 'course lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('name', models.CharField(max_length=100, verbose_name='video name')),
                ('file', models.FileField(max_length=200, upload_to='test', verbose_name='video file')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'course video',
                'verbose_name_plural': 'course video',
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time')),
                ('name', models.CharField(max_length=50, verbose_name='course resources')),
                ('file', models.FileField(max_length=200, upload_to='test', verbose_name='course resources file')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'course resources',
                'verbose_name_plural': 'course resources',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lecturer', verbose_name='lecturer'),
        ),
    ]
