# Generated by Django 2.2 on 2022-03-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(max_length=200, upload_to='courses/resources/', verbose_name='course resources file'),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='file',
            field=models.FileField(max_length=200, upload_to='courses/video/', verbose_name='video file'),
        ),
    ]
