# Generated by Django 2.2 on 2022-01-09 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220109_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time'),
        ),
    ]
