# Generated by Django 2.2 on 2022-01-08 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20220108_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added time'),
        ),
    ]
